### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by kidkuro** [gemini-testing/gemini-core#43]
To support TypeScript we only need to add `.ts` to https://github.com/gemini-testing/gemini-core/blob/master/lib/sets-builder/index.js#L11

We could also look at refactoring to get the formats from the gemini config sets.

We could raise an initial PR with the trivial fix, and then look into whether the more robust solution is feasible.

We're also happy to add the types to DefinitelyTyped and to publish a gemini-typescript plugin.

**Comment by sipayRT** [comment]
hi

can you send PR with your fixes?

**Comment by DudaGod** [comment]
Hello.
Hermione already supports the ability to read TS files - https://github.com/gemini-testing/hermione#fileExtensions.
Moreover you can use `--require` option to compile ts files on the fly - https://github.com/gemini-testing/hermione#require-modules.
